name: Deploy to GitHub Pages

on:
  push:
    branch: 
      - main
    release:
      types:
        - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
        #  - name: Setup NodeJS
        #uses: actions/setup-node@v3
        #with:
        #node-version: 14
        #cache: 'npm'
        # cache-dependency-path: subdir/package-lock.json
    
        # - name: Run node CI & Tests
        # - run: | 
        #  npm ci
    
    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: mitre/inspec-assessor
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm ci && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/

